title: Michelle Natasya Tanuwijaya
logo: images/Foto_Michelle Natasya.jpeg
description: An organized, thorough, and detail-oriented person who was willing to learn new things in new environments. Quick learner with the ability to handle multiple tasks simultaneously, adapt to a variety of challenges. Highly enthused about environmental issues, social acts, planning and organizing.
<br><br>
  <a href="https://www.linkedin.com/in/michelle-natasya/">View My LinkedIn Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
